<main id="about">
    <section class="section1About">
        <div class="aboutDIV">
        <h4>Mentions légales</h4>
            <div class="legalsInfos">
                <div>
                    <h5>Éditeur</h5>
                    <p>Site ArcadiaZoo est un site réalisé par DaBill.<br>
                    Siège social : Le Boulay-Morin - 27930 - France.<br>
                    Tél. : + 33 6 62 67 16 43<br>
                    Directeur de publication : Damien Billiau<br>
                    <a href="#imgCredits">Crédits images</a><br>
                    Photos : unsplash.com</p>
                </div>
                <div>
                    <h5>Hébergeur de site</h5>
                    <p>HEROKU<br>
                    <a href="https://www.salesforce.com/fr/">salesforce.com France S.A.S</a>
                    3 Avenue Octave Gréard<br>
                    75007 Paris<br>
                    Main: +33 17-670-5590<br>
                    Fax: +33 (0)1 72 10 94 01<br>
                    Sales: Numero Vert : 00800 7253 3333<br>
                </div>
            </div>
        </div>
        <div class="CGUDIV">
            <h4>Conditions générales d'utilisation</h4>
            <div>
            <p>L'utilisation du site <b>ArcadiaZoo</b> implique l'acceptation pleine et entière des conditions générales d'utilisation ci-après décrites. Ces conditions d'utilisation sont susceptibles d'être modifiées ou complétées à tout moment, les utilisateurs du site sont donc invités à les consulter de manière régulière.
                Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par la société Dabill, qui s'efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l'intervention.
                Le site <b>ArcadiaZoo</b> est mis à jour régulièrement. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s'imposent néanmoins à l'utilisateur qui est invité à s'y référer le plus souvent possible afin d'en prendre connaissance.</p>
                <h5>Description des services fournis</h5>
                <p>La société DaBill s'efforce de fournir sur son site internet des informations aussi précises que possible. Toutefois, il ne pourra être tenue responsable des omissions, des inexactitudes et des carences dans la mise à jour, qu'elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.
                Tous les informations indiquées sur le site internet sont données à titre indicatif, et sont susceptibles d'évoluer. Par ailleurs, les renseignements figurant sur le site DaBill ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
                <h5>Politique de confidentialité et gestion des données personnelles</h5>
                <p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995 ainsi que par le RGPD.
                La société DaBill collecte des informations personnelles relatives à l'utilisateur via son formulaire de contact et de demande de devis. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il rempli de lui-même les champs des formulaires. Il est alors précisé à l'utilisateur du site l'obligation ou non de fournir ces informations.
                Les informations recueillies sur ce formulaire sont enregistrées par l'équipe informatique de la société DaBill. Elles peuvent être conservées sur des serveurs de messagerie sécurisée et sont destinées uniquement aux échanges par email, ou téléphone entre la responsable du site et les internautes.
                Les données recueillies sur le site DaBill lors de l'envoi d'un email sont strictement réservées au responsable du site et à son équipe et ne seront en aucun cas cédées ou vendues à des tiers. Aucune adresse email ou donnée personnelle ne sera transmise à des tiers ou des partenaires, sauf avec l'accord écrit des intéressés.
                L'ensemble du site ainsi que sa base de données sont protégés par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
                <h5>Limitations contractuelles sur les données techniques</h5>
                <p>Le site Internet de la société DaBill ne pourra être tenu responsable de dommages matériels liés à l'utilisation du site. De plus, l'utilisateur du site s'engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour.</p>
                <h5>Propriété intellectuelle et contrefaçons</h5>
                <p>La société DaBill est propriétaire des droits de propriété intellectuelle ou détient les droits d'usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes.
                Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de la part de la société.
                Toute exploitation non autorisée du site ou de l'un quelconque des éléments qu'il contient sera considérée comme constitutive d'une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
                <h5>Limitations de responsabilité</h5>
                La société DaBill ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l'utilisateur, lors de l'accès au site, et résultant soit de l'utilisation d'un matériel ne répondant pas aux spécifications traditionnelles de navigation web, soit de l'apparition d'un bug ou d'une incompatibilité.
                La société DaBill ne pourra également être tenue responsable des dommages indirects (tels par exemple qu'une perte de marché ou perte d'une chance) consécutifs à l'utilisation du site DaBill.
                <h5>Liens hypertextes</h5>
                Le site <b>ArcadiaZoo</b> contient un certain nombre de liens hypertextes vers d'autres sites. Cependant, la société DaBill n'a pas la possibilité de vérifier le contenu des sites ainsi visités, et n'assumera en conséquence aucune responsabilité de ce fait.
                <h5>Droit applicable et attribution de juridiction</h5>
                Tout litige en relation avec l'utilisation du site <b>ArcadiaZoo</b> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.
                <h5>Analyses des visites sur notre site</h5>
                Nous pouvons utiliser des services d'analyse des visites pour mesurer les visites des internautes. Les informations qui peuvent être enregistrées sont : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au site, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur, le système informatique de l'utilisateur. Ces analyses de visites fonctionnent via les cookies, elles sont stockées sur les serveurs de Google pour une durée de 26 mois, et il vous trouverez toutes les explications concernant leur utilisation ou leur refus plus bas sur cette page.
                <h5>Déclaration relative à l'utilisation de cookies sur ce site internet</h5>
                La navigation sur le site <b>ArcadiaZoo</b> est susceptible de provoquer l'installation de cookie(s) sur l'ordinateur de l'utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l'identification de l'utilisateur, mais qui enregistre des informations relatives à la navigation d'un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.
                Le refus d'installation d'un cookie peut entraîner l'impossibilité d'accéder à certains services. L'utilisateur peut toutefois configurer son ordinateur pour refuser l'installation des cookies.
                <h5>C'est quoi un cookie, ça se mange ?</h5>
                <p>Le gâteau oui ! Mais pas ceux utilisés sur le site <b>ArcadiaZoo</b> 😉 Les cookies sont des petits éléments d'information envoyés à partir d'un site Internet et stockés sur l'ordinateur de l'utilisateur lors de sa visite sur ce site. Les cookies remplissent de nombreuses fonctions, comme celles d'informer le site Internet de votre activité antérieure sur le site de façon à rendre votre utilisation du site plus efficace et plus conviviale, de se souvenir de vos préférences, de vous permettre de naviguer sur le site, et de vous authentifier si vous vous êtes inscrit(e) sur le site ou si vous cherchez à réaliser un achat par l'intermédiaire de ce site. Les cookies peuvent également faire en sorte que les publicités que vous voyez en ligne soient mieux adaptées à vous-même et à vos intérêts.
                L'utilisation des cookies n'endommage en aucune façon votre ordinateur et sont en général automatiquement supprimés au bout d'un certain temps, par exemple six mois. Vous trouverez de plus amples informations concernant les cookies sur le site : www.allaboutcookies.org.
                <h5>DaBill utilise-t-il des cookies sur son site internet ?</h5>
                Oui, comme la plupart des sites. Cela nous permet de détecter qu'un même utilisateur est revenu sur notre site, de savoir combien d'utilisateurs ont visité notre site, quelles pages ont été consultées et s'il y a eu des problèmes techniques lors du chargement des pages ou de la navigation sur le site. Grâce à la collecte de ces informations, nous pouvons savoir quelles sont les parties de notre site qui présentent le plus d'intérêt et d'utilité pour nos utilisateurs, et surveiller l'intérêt global généré par notre site internet. Cela nous permet également d'identifier des problèmes techniques liés au site, de façon à pouvoir les résoudre dans les meilleurs délais. En retour, cela nous aide à assurer le bon fonctionnement de notre site internet et à améliorer l'offre que nous proposons à nos visiteurs.
                <h5>Suis-je obligé(e) d'accepter les cookies ?</h5>
                Non. Vous pouvez désactiver l'utilisation des cookies, y compris ceux utilisés sur notre site internet, en désactivant la fonction cookie de votre navigateur. Cependant, certaines parties de notre site, de même que la plupart des autres sites, ne fonctionneront pas correctement si vous optez pour cette solution.
                <h5>Quels types de cookies sont utilisés par ce site ?</h5>
                Trois grandes catégories de cookies sont utilisées sur nos sites internet :
                · Cookies strictement nécessaires (ou essentiels). Ces cookies sont essentiels pour vous permettre de naviguer sur un site internet et utiliser ses fonctions. Comme tous les sites internet publics, notre site utilise des cookies strictement nécessaires.
                · Cookies de performance. Ces cookies collectent des informations sur la manière dont les visiteurs utilisent un site internet, et permettent de savoir par exemple quelles sont les pages le plus souvent consultées par les utilisateurs, et si ceux-ci reçoivent des messages d'erreurs de certaines pages web. Ces cookies ne collectent pas d'informations identifiant le visiteur. Les informations collectées sont agrégées et anonymes, et ne sont utilisées que pour améliorer le fonctionnement du site internet. Comme presque tous les sites internet, nous utilisons des cookies de performance sur nos sites.
                · Cookies de fonctionnalité. Ces cookies permettent au site internet de se souvenir des choix que vous faites (tels que votre nom d'utilisateur, votre langue ou la région dans laquelle vous vous trouvez). En retour, cela permet au site de vous fournir des fonctions améliorées et plus personnelles, et d'améliorer ainsi votre visite sur ce site. Les informations collectées par ces cookies sont généralement anonymes et n'incluent pas votre activité de navigation sur d'autres sites internet. Comme presque tous les sites internet, nous utilisons des cookies de fonctionnalité sur nos sites.
                <h5>Que se passe-t-il si j'autorise les cookies sur mon navigateur ?</h5>
                À moins que ces fonctions ne soient désactivées, en utilisant notre site internet et les services en ligne, vous nous autorisez à installer des cookies et les technologies associées sur votre ordinateur.
                <h5>La société DaBill autorise-t-elle des tiers à installer des cookies ou autres technologies similaires sur ses sites internet ?</h5>
                En règle générale, nous n'autorisons pas les tiers (tels que les annonceurs) à installer des cookies sur nos sites internet ou à se livrer à de la publicité comportementale. Cependant, sur certains de nos sites internet tels que nos pages de réseaux sociaux, il est possible que des personnes aient téléchargé le contenu de tiers, tels que des vidéos de YouTube ou autres, ou intégré du contenu et des outils de partage provenant d'autres sites tiers. Comme nous ne contrôlons pas la diffusion des cookies par des sites qui n'appartiennent pas et ne sont pas exploités par DaBill, vous devrez contrôler le(s) site(s) internet tiers pertinent(s) pour en savoir plus sur ces cookies, pour savoir s'il est possible de refuser de les recevoir, et quelle est la manière de le faire. Cependant, vous pouvez en général désactiver les cookies de tiers en réglant les paramètres de votre navigateur. Vous trouverez des instructions à ce sujet sur le site : www.aboutcookies.org.
            </div>
        </div>
        <div class="imgCredits" id="imgCredits">
        <h4>Crédit images</h4>
        <ul>
            <li>cervides.jpg - Photo de <a href="https://unsplash.com/fr/@daiga_ellaby?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Daiga Ellaby</a> sur <a href="https://unsplash.com/fr/photos/garcon-nourrissant-un-animal-pendant-la-journee-Sg_OwwU2Z9o?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>fox.jpg - Photo de <a href="https://unsplash.com/fr/@rayhennessy?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Ray Hennessy</a> sur <a href="https://unsplash.com/fr/photos/brown-fox-on-snow-field-xUUZcpQlqpM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>giraf.jpg - Photo de <a href="https://unsplash.com/fr/@thoeva?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Thomas Evans</a> sur <a href="https://unsplash.com/fr/photos/girafe-marchant-sur-une-friche-industrielle-pendant-la-journee-NVXY8_M1n40?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>canadianForest.jpg - Photo de <a href="https://unsplash.com/fr/@yannallegre?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Yann Allegre</a> sur <a href="https://unsplash.com/fr/photos/pont-en-bois-marron-jYp7Nwew9KQ?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>jungle.jpg - Photo de <a href="https://unsplash.com/fr/@isaacquesada?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Isaac Quesada</a> sur <a href="https://unsplash.com/fr/photos/chemin-de-terre-brun-entre-les-plantes-vertes-pendant-la-journee-6xxxvB72qB0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>restaurant.jpg - Photo de <a href="https://unsplash.com/fr/@pinchebesu?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Ruben Ramirez</a> sur <a href="https://unsplash.com/fr/photos/table-et-chaises-en-bois-marron-xhKG01FN2uk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>womenMap.jpg - Photo de <a href="https://unsplash.com/fr/@eliomendes?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Elio Santos</a> sur <a href="https://unsplash.com/fr/photos/femme-portant-un-manteau-gris-debout-sur-le-trottoir-de-brique-q7pOFt3J0ks?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>anticTrain.jpg - Photo de <a href="https://unsplash.com/fr/@rickyrynselo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Ricky LK</a> sur <a href="https://unsplash.com/fr/photos/un-train-rouge-descendant-les-voies-ferrees-a-cote-dune-foret-qL7uzkey6ho?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>swamp.jpg - Photo de <a href="https://unsplash.com/fr/@markusspiske?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Markus Spiske</a> sur <a href="https://unsplash.com/fr/photos/lac-bleu-entoure-darbres-d8duf9ndLxE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>savannah.jpg - Photo de <a href="https://unsplash.com/fr/@davidclode?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Clode</a> sur <a href="https://unsplash.com/fr/photos/arbres-a-feuilles-vertes-92MgFhlWD-8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>

            <li>lion.jpg - Photo de <a href="https://unsplash.com/fr/@jwimmerli?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">jean wimmerlin</a> sur <a href="https://unsplash.com/fr/photos/photographie-de-mise-au-point-peu-profonde-de-lion-a-la-faune-FC4GY9nQuu0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>guepard.jpg - Photo de <a href="https://unsplash.com/fr/@pumplekin?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Groves</a> sur <a href="https://unsplash.com/fr/photos/guepard-sur-un-champ-dherbe-bcJUbYd5gTo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>léopard.jpg - Photo de <a href="https://unsplash.com/fr/@veverkolog?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Dušan veverkolog</a> sur <a href="https://unsplash.com/fr/photos/leopard-brun-et-noir-sur-branche-darbre-brune-pendant-la-journee-RhNGJT6oNlA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>elephant.jpg - Photo de <a href="https://unsplash.com/fr/@bepnamanh?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Nam Anh</a> sur <a href="https://unsplash.com/fr/photos/marche-a-dos-delephant-pendant-la-journee-QJbyG6O0ick?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>girafe.jpg - Photo de <a href="https://unsplash.com/fr/@mariolagr?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mariola Grobelska</a> sur <a href="https://unsplash.com/fr/photos/trois-girafes-sur-un-champ-dherbe-brune-pendant-la-journee-eQdDUdi5qLk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>zebre.jpg - Photo de <a href="https://unsplash.com/fr/@dtomaseti?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Tomaseti</a> sur <a href="https://unsplash.com/fr/photos/zebre-debout-sur-lherbe-verte-pendant-la-journee-Vw2HZQ1FGjU?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>gnou.jpg - Photo de <a href="https://unsplash.com/fr/@sirloinchop?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Pieter van Noorden</a> sur <a href="https://unsplash.com/fr/photos/troupeau-de-buffles-deau-sur-le-terrain-pendant-la-journee-tUJRq7ofFmI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>hyene.jpg - Photo de <a href="https://unsplash.com/fr/@davidclode?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Clode</a> sur <a href="https://unsplash.com/fr/photos/deux-hyenes-brunes-couchees-sur-un-sol-brun-pendant-la-journee-a3iIUJcKXOI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>gazelle.jpg - Photo de <a href="https://unsplash.com/fr/@jaliya?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jaliya Rasaputra</a> sur <a href="https://unsplash.com/fr/photos/gazelle-brune-blanche-et-noire-sur-sable-brun-pendant-la-journee-Y5Kjgbd3hKA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>chimpanzee.jpg - Photo de <a href="https://unsplash.com/fr/@dtrinksrph?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Trinks</a> sur <a href="https://unsplash.com/fr/photos/un-singe-noir-assis-sur-une-branche-darbre-pFEKeg4xjUA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>tigre.jpg - Photo de <a href="https://unsplash.com/fr/@agord70345203222008?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">A G</a> sur <a href="https://unsplash.com/fr/photos/tigre-brun-et-noir-sur-la-photographie-de-mise-au-point-YuQgNYku1M8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>perroquet.jpg - Photo de <a href="https://unsplash.com/fr/@kevinmueller?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Kevin Mueller</a> sur <a href="https://unsplash.com/fr/photos/perroquet-orange-aeNg4YA41P8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>elephantAsie.jpg - Photo de <a href="https://unsplash.com/fr/@teodorpk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Teodor Kuduschiev</a> sur <a href="https://unsplash.com/fr/photos/un-elephant-avec-des-defenses-wlkdA3D6lKA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>tapir.jpg - Photo de <a href="https://unsplash.com/fr/@crespo_photography101?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">David Duarte Crespo</a> sur <a href="https://unsplash.com/fr/photos/un-animal-brun-dans-un-champ-jrCCPkfAp1c?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>paresseux.jpg - Photo de <a href="https://unsplash.com/fr/@jackcharles?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jack Charles</a> sur <a href="https://unsplash.com/fr/photos/singe-gris-et-brun-sur-une-branche-darbre-pendant-la-journee-qmYTIcJ82qk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>serpent.jpg - Photo de <a href="https://unsplash.com/fr/@markstoop?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mark Stoop</a> sur <a href="https://unsplash.com/fr/photos/serpent-noir-et-blanc-sur-arbre-vert-cZfNUotqzBI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>gorille.jpg - Photo de <a href="https://unsplash.com/fr/@amybethreed?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Amy Reed</a> sur <a href="https://unsplash.com/fr/photos/gorille-noir-debout-derriere-le-rocher-XB5E4D-Ipco?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>orangOutan.jpg - Photo de <a href="https://unsplash.com/fr/@patwhelen?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Pat Whelen</a> sur <a href="https://unsplash.com/fr/photos/singe-brun-suspendu-a-une-branche-darbre-pendant-la-journee-7h4yibuV3Ms?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>crocodile.jpg - Photo de <a href="https://unsplash.com/fr/@lisaleo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Lisa Yount</a> sur <a href="https://unsplash.com/fr/photos/crocodile-noir-sur-leau-pendant-la-journee-POKb4uUOizU?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>heron_cendre.jpg - Photo de <a href="https://unsplash.com/fr/@hirmin?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Max Kleinen</a> sur <a href="https://unsplash.com/fr/photos/photographie-selective-dun-oiseau-pres-dun-plan-deau-Cu13_98qj38?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>alligator.jpg - Photo de <a href="https://unsplash.com/fr/@eyedealstuff?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Shelly Collins</a> sur <a href="https://unsplash.com/fr/photos/crocodile-dans-le-plan-deau-YppMBEPyfFQ?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>tortue_floride.jpg - Photo de <a href="https://unsplash.com/fr/@probablyrobin?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Robin Teng</a> sur <a href="https://unsplash.com/fr/photos/une-tortue-est-assise-sur-une-buche-dans-leau-uak0AKRv9uo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>aigrette_garzette.jpg - Photo de <a href="https://unsplash.com/fr/@sonika_agarwal?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Sonika Agarwal</a> sur <a href="https://unsplash.com/fr/photos/oiseau-blanc-sur-leau-pendant-la-journee-w__n1LHMgsc?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>ragondin.jpg - Photo de <a href="https://unsplash.com/fr/@limosa?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Šárka Krňávková</a> sur <a href="https://unsplash.com/fr/photos/animal-brun-et-noir-dans-leau-LiVczGqKF_8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>grenouille_taureau.jpg - Photo de <a href="https://unsplash.com/fr/@dawnoftime?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Aurora K</a> sur <a href="https://unsplash.com/fr/photos/une-grenouille-sur-un-rocher-m4pCrp9PbIM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>carpe_commune.jpg - Photo de <a href="https://unsplash.com/fr/@stereophototyp?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Sara Kurfeß</a> sur <a href="https://unsplash.com/fr/photos/poisson-gris-pres-de-rocher-Pcjf94H451o?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
            <li>sanglier.jpg - Photo de <a href="https://unsplash.com/fr/@anetvob?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Aneta Voborilova</a> sur <a href="https://unsplash.com/fr/photos/animal-brun-a-4-pattes-sur-un-sol-enneige-pendant-la-journee-KDmzjXA9XP8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></li>
        </ul><br>
    </section>